### ISSUE TITLE
ECONNABORTED inside Actions only

### ISSUE THREAD

**Issue by joshghent** [LironEr/bundlemon-github-actions#10]
Hi there! Thanks for a great tool and guide :) 

It works great locally but unfortunately get the following error inside Github Actions

```
2022-03-17T12:23:58.0972640Z [36;1myarn bundlemon[0m
2022-03-17T12:23:58.1029770Z shell: /usr/bin/bash -e {0}
2022-03-17T12:23:58.1030003Z env:
2022-03-17T12:23:58.1031955Z   BUNDLEMON_PROJECT_ID: 62331be164b23784215e72cb
2022-03-17T12:23:58.1032363Z   BUNDLEMON_PROJECT_APIKEY: ***
2022-03-17T12:23:58.1032644Z   CI_COMMIT_SHA: 230657b99f98f6f2880319839deab9e6091c7532
2022-03-17T12:23:58.1032904Z ##[endgroup]
2022-03-17T12:23:58.2482198Z yarn run v1.22.17
2022-03-17T12:23:58.2786277Z $ /home/runner/work/homepage/homepage/node_modules/.bin/bundlemon
2022-03-17T12:23:58.4577112Z [INFO] Start BundleMon v1.3.1
2022-03-17T12:23:58.4657932Z [INFO] base directory: "/home/runner/work/homepage/homepage/.next"
2022-03-17T12:23:58.4671203Z [INFO] Start analyzing
2022-03-17T12:23:58.5349813Z [INFO] Finished analyzing
2022-03-17T12:23:58.5354377Z [INFO] Start generating report
2022-03-17T12:23:58.5356210Z [INFO] Create commit record for branch "feat/2691-bundlesize"
2022-03-17T12:24:05.5614300Z [ERROR] create commit record: Cant reach server (https://api.bundlemon.dev) code "ECONNABORTED"
2022-03-17T12:24:05.5614859Z [ERROR] Failed to create commit record
2022-03-17T12:24:05.5615195Z [ERROR] Unhandled error
2022-03-17T12:24:05.5633637Z Error: Failed to generate report
2022-03-17T12:24:05.5634168Z     at /home/runner/work/homepage/homepage/node_modules/bundlemon/lib/main/index.js:32:15
2022-03-17T12:24:05.5634611Z     at Generator.next (<anonymous>)
2022-03-17T12:24:05.5635123Z     at fulfilled (/home/runner/work/homepage/homepage/node_modules/bundlemon/lib/main/index.js:5:58)
2022-03-17T12:24:05.5635691Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-17T12:24:05.5798990Z error Command failed with exit code 1.
2022-03-17T12:24:05.5799550Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-03-17T12:24:05.5885230Z ##[error]Process completed with exit code 1.
```

Thanks in advance ❤️

**Comment by LironEr** [comment]
Is it still happening?
I didn't see problems with connecting to the API yet

**Comment by joshghent** [comment]
Hey! So sorry, I forgot to close this issue.
Turns out, Github Actions was experiencing issues at the time. Appears to be working now! Thanks again :)
